title: A Song of Ice and Fire - Quotes
author: alaameskine
email: al2a.meskine@gmail.com
theme: jekyll-theme-tactile
description: > # this means to ignore newlines until "baseurl:"
  This new site contains some of the mythical quotes in the Game of Thrones universe, whether it's from the TV show
  or the exceptionally well-written books by George R R Martin.

# social links
twitter_username: AlaaMeskine # DO NOT include the @ character, or else the build will fail!
github_username:  alaameskine # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
